# Informações do Projeto
site_name: Associação Nacional dos Agricultores Extrativista, Quilombolas e Indígenas da Amazônia
site_author: Aylton Aguiar
site_description: >-
    <p> Associação Nacional dos Agricultores Extrativista, Quilombolas e  Indígenas  da Amazônia, também representada pela sigla AEQIA.
    Fundada em 06 de agosto de 2011.</p>
    <p> Por natureza de pessoa jurídica de direito privado, de fins não econômicos, com duração por tempo indeterminado,
     com sua sede na Rodovia Macapá Mazagão Km 30 nº422, município de Santana Estado do Amapá, e Foro na Comarca de Santana, Estado do Amapá, Brasil.
    </p>
    <br><br>

# Configurações
theme: 
  name: material
  custom_dir: !ENV [THEME_DIR, "material"]

  include_search_page: false
  search_index_only: true

  static_templates:
    - 404.html
  
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    #- toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/leaf

# Plugins
plugins:
  - search
  - table-reader:
      data_path: "docs/assets/tables"

# Extensões
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: AyltonAguiar
      repo: northwind
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Árvore de Navegação
nav:
    - Início: index.md
    - AEQIA tem por finalidade:
      - src/finalidade.md